version: "3.9"

services:
    
    mysql:
        image: mysql:8.0.24
        container_name: mysql-container
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql-database
        volumes:
            - mysql-data:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d

    mongo:
        image: mongo:4.4.5
        container_name: mongo-container
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: mongo-database
        volumes:
            - mongo-data:/data/db
            - ./.docker/mongo:/docker-entrypoint-initdb.d

    app:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
        depends_on: 
            - mysql
            - mongo

volumes:
    mysql-data:
    mongo-data: